version: '0.2'

phases:
  install:
    commands:
      - "echo 'Installing dependencies if any...'"
  build:
    commands:
      - "echo 'Starting build...'"
      - "echo 'X Value: $X'"
      - "echo 'Y Value: $Y'"
      - "ls"
      - "python tenant/modelmonitoring/test-xfactrs-summation.py $X $Y"

artifacts:
  files:
    - '**/*'
