Description:
  This template is built and deployed by the infrastructure pipeline in various stages (staging/production) as required.
  It specifies the resources that need to be created. In this case, an EventBridge Rule, a SageMaker Pipelines and a
  SageMake Model.
Parameters:
  UseCase:
    Type: String
    Description: Variables passed at pipeline level
  Algorithm:
    Type: String
    Description: Variables passed at pipeline level
  Tenant:
    Type: String
    Description: Variables passed at pipeline level
  ContainerImage:
    Type: String
    Description: Image used for the SageMaker Model
  SageMakerProjectName:
    Type: String
    Description: Name of the project (lower case)
    MinLength: 1
    MaxLength: 32
    AllowedPattern: ^[a-z](-*[a-z0-9])*
  SageMakerProjectId:
    Type: String
    Description: Id of the project
    MinLength: 1
    MaxLength: 32
  ModelExecutionRoleArn:
    Type: String
    Description: Execution role used for deploying the model.
  ModelDataUrl:
    Type: String
    Description: S3 location for the model
  ModelName:
    Type: String
    Description: SageMaker Model Name
  InputPath:
    Type: String
    Description: The S3 path where data is stored on which to run inference.
  OutputPath:
    Type: String
    Description: The S3 path where predictions will be output.
  ScheduleExpressionforPipeline:
    Type: String
    Description: The rate of execution of your pipeline (default 30 minutes)
    Default: 30 minutes
  StageName:
    Type: String
    Description:
      The name for a project pipeline stage, such as dev or prod, for
      which resources are provisioned and deployed.
  PipelineDefinitionBody:
    Type: String
    Description:
      The body of the SageMaker Pipeline.
# Conditions:
#   ModelDeploy: !Equals [!Ref StageName, staging]
Resources:
  Model:
    Type: AWS::SageMaker::Model
    Properties:
      EnableNetworkIsolation: false
      ExecutionRoleArn:
        Ref: ModelExecutionRoleArn
      ModelName: !Ref ModelName
      PrimaryContainer:
        Mode: SingleModel
        Image: !Ref ContainerImage
        ModelDataUrl: !Ref ModelDataUrl
  BatchPipeline:
    Type: AWS::SageMaker::Pipeline
    DependsOn:
      - Model
    Properties:
      PipelineDescription: The SM Pipeline that executes the batch inference for model
      PipelineName: !Sub ${SageMakerProjectName}-${StageName}-${ModelName}-BatchPipeline
      RoleArn: !Ref ModelExecutionRoleArn
      PipelineDefinition: 
        PipelineDefinitionBody: !Ref PipelineDefinitionBody
      Tags:
        - Key: sagemaker:project-name
          Value: !Ref SageMakerProjectName
        - Key: sagemaker:project-id
          Value: !Ref SageMakerProjectId

#   EventRule:
#     Type: AWS::Events::Rule
#     DependsOn:
#       - BatchPipeline
#     Properties:
#       Name: !Sub sagemaker-${SageMakerProjectName}-${StageName}-SchedExecRule
#       ScheduleExpression: !Sub rate(${ScheduleExpressionforPipeline})
#       Targets:
#         - Arn: !Sub arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:pipeline/${SageMakerProjectName}-${StageName}-BatchPipeline
#           Id: MyBatchInferenceTarget
#           RoleArn: !Ref ModelExecutionRoleArn
#           SageMakerPipelineParameters:
#             PipelineParameterList:
#               - Name: InputPath
#                 Value: !Ref InputPath
#               - Name: OutputPath
#                 Value: !Ref OutputPath


Outputs:
  SagemakerModelName:
    Description: Name of Model to be deployed
    Value: !Ref ModelName
    Export:
      Name: !Sub sagemaker-model-${ModelName}